// data.js
export const defaultData = [
  {
    "Customer Name": "Romona Heaslip",
    Model: "Taurus",
    Color: "Aquamarine",
    "Payment Mode": "Debit Card",
    "Delivery Date": "07/11/2015",
    Amount: "8529.22",
  },
  {
    "Customer Name": "Clare Batterton",
    Model: "Sparrow",
    Color: "Pink",
    "Payment Mode": "Cash On Delivery",
    "Delivery Date": "7/13/2016",
    Amount: "17866.19",
  },
  {
    "Customer Name": "Eamon Traise",
    Model: "Grand Cherokee",
    Color: "Blue",
    "Payment Mode": "Net Banking",
    "Delivery Date": "09/04/2015",
    Amount: "13853.09",
  },
  {
    "Customer Name": "Julius Gorner",
    Model: "GTO",
    Color: "Aquamarine",
    "Payment Mode": "Credit Card",
    "Delivery Date": "12/15/2017",
    Amount: "2338.74",
  },
  {
    "Customer Name": "Jenna Schoolfield",
    Model: "LX",
    Color: "Yellow",
    "Payment Mode": "Credit Card",
    "Delivery Date": "10/08/2014",
    Amount: "9578.45",
  },
  {
    "Customer Name": "Marylynne Harring",
    Model: "Catera",
    Color: "Green",
    "Payment Mode": "Cash On Delivery",
    "Delivery Date": "7/01/2017",
    Amount: "19141.62",
  },
  {
    "Customer Name": "Vilhelmina Leipelt",
    Model: "7 Series",
    Color: "Goldenrod",
    "Payment Mode": "Credit Card",
    "Delivery Date": "12/20/2015",
    Amount: "6543.30",
  },
  {
    "Customer Name": "Barby Heisler",
    Model: "Corvette",
    Color: "Red",
    "Payment Mode": "Credit Card",
    "Delivery Date": "11/24/2014",
    Amount: "13035.06",
  },
  {
    "Customer Name": "Karyn Boik",
    Model: "Regal",
    Color: "Indigo",
    "Payment Mode": "Debit Card",
    "Delivery Date": "05/12/2014",
    Amount: "18488.80",
  },
  {
    "Customer Name": "Jeanette Pamplin",
    Model: "S4",
    Color: "Fuscia",
    "Payment Mode": "Net Banking",
    "Delivery Date": "12/30/2014",
    Amount: "12317.04",
  },
  {
    "Customer Name": "Cristi Espinos",
    Model: "TL",
    Color: "Aquamarine",
    "Payment Mode": "Credit Card",
    "Delivery Date": "12/18/2013",
    Amount: "6230.13",
  },
  {
    "Customer Name": "Issy Humm",
    Model: "Club Wagon",
    Color: "Pink",
    "Payment Mode": "Cash On Delivery",
    "Delivery Date": "02/02/2015",
    Amount: "9709.49",
  },
  {
    "Customer Name": "Tuesday Fautly",
    Model: "V8 Vantage",
    Color: "Crimson",
    "Payment Mode": "Debit Card",
    "Delivery Date": "11/19/2014",
    Amount: "9766.10",
  },
  {
    "Customer Name": "Rosemaria Thomann",
    Model: "Caravan",
    Color: "Violet",
    "Payment Mode": "Net Banking",
    "Delivery Date": "02/08/2014",
    Amount: "7685.49",
  },
  {
    "Customer Name": "Lyell Fuentez",
    Model: "Bravada",
    Color: "Violet",
    "Payment Mode": "Debit Card",
    "Delivery Date": "08/05/2016",
    Amount: "18012.45",
  },
  {
    "Customer Name": "Raynell Layne",
    Model: "Colorado",
    Color: "Pink",
    "Payment Mode": "Credit Card",
    "Delivery Date": "05/30/2016",
    Amount: "2785.49",
  },
  {
    "Customer Name": "Raye Whines",
    Model: "4Runner",
    Color: "Red",
    "Payment Mode": "Debit Card",
    "Delivery Date": "12/10/2016",
    Amount: "9967.74",
  },
  {
    "Customer Name": "Virgina Aharoni",
    Model: "TSX",
    Color: "Pink",
    "Payment Mode": "Cash On Delivery",
    "Delivery Date": "10/23/2014",
    Amount: "5584.33",
  },
  {
    "Customer Name": "Peta Cheshir",
    Model: "Pathfinder",
    Color: "Red",
    "Payment Mode": "Net Banking",
    "Delivery Date": "12/24/2015",
    Amount: "5286.53",
  },
  {
    "Customer Name": "Jule Urion",
    Model: "Charger",
    Color: "Violet",
    "Payment Mode": "Debit Card",
    "Delivery Date": "11/20/2013",
    Amount: "13511.91",
  },
  {
    "Customer Name": "Lew Gilyatt",
    Model: "Bonneville",
    Color: "Crimson",
    "Payment Mode": "Credit Card",
    "Delivery Date": "11/19/2013",
    Amount: "6498.19",
  },
  {
    "Customer Name": "Jobey Fortun",
    Model: "B-Series",
    Color: "Blue",
    "Payment Mode": "Net Banking",
    "Delivery Date": "10/30/2014",
    Amount: "10359.67",
  },
  {
    "Customer Name": "Blondie Crump",
    Model: "Voyager",
    Color: "Turquoise",
    "Payment Mode": "Credit Card",
    "Delivery Date": "04/06/2018",
    Amount: "8118.39",
  },
  {
    "Customer Name": "Florentia Binns",
    Model: "Grand Prix",
    Color: "Orange",
    "Payment Mode": "Cash On Delivery",
    "Delivery Date": "10/13/2016",
    Amount: "10204.37",
  },
  {
    "Customer Name": "Jaquelin Galtone",
    Model: "Sunbird",
    Color: "Red",
    "Payment Mode": "Net Banking",
    "Delivery Date": "10/22/2013",
    Amount: "6528.06",
  },
  {
    "Customer Name": "Hakeem Easseby",
    Model: "Mirage",
    Color: "Crimson",
    "Payment Mode": "Debit Card",
    "Delivery Date": "9/12/2014",
    Amount: "5619.25",
  },
  {
    "Customer Name": "Nickolaus Gidman",
    Model: "XK",
    Color: "Orange",
    "Payment Mode": "Debit Card",
    "Delivery Date": "05/12/2016",
    Amount: "5091.43",
  },
  {
    "Customer Name": "Jenine Iglesia",
    Model: "Accord",
    Color: "Orange",
    "Payment Mode": "Debit Card",
    "Delivery Date": "09/03/2018",
    Amount: "14566.08",
  },
  {
    "Customer Name": "Fax Witherspoon",
    Model: "Range Rover Sport",
    Color: "Orange",
    "Payment Mode": "Credit Card",
    "Delivery Date": "2/22/2018",
    Amount: "5284.87",
  },
];
// data.js
export const FormattingData = [
  {
    "Item Code": "AG940Z",
    "Item Name": "Laser Printer",
    Quantity: "144",
    "Purchase Price": "169.50",
    "Selling Price": "172",
    Profit: "=E3-D3",
    "Last Updated": "5/25/19",
    Rating: "4.5",
  },
  {
    "Item Code": "BJ120K",
    "Item Name": "Scientific Calculator",
    Quantity: "116",
    "Purchase Price": "21.80",
    "Selling Price": "23",
    Profit: "=E4-D4",
    "Last Updated": "7/28/19",
    Rating: "4.0",
  },
  {
    "Item Code": "BC120M",
    "Item Name": "Wired Keyboard",
    Quantity: "438",
    "Purchase Price": "26.80",
    "Selling Price": "29",
    Profit: "=E5-D5",
    "Last Updated": "3/30/20",
    Rating: "4.25",
  },
  {
    "Item Code": "BS121L",
    "Item Name": "Memory Card",
    Quantity: "486",
    "Purchase Price": "23.50",
    "Selling Price": "25",
    Profit: "=E6-D6",
    "Last Updated": "8/20/19",
    Rating: "3.5",
  },
  {
    "Item Code": "BU121K",
    "Item Name": "Coffee Maker",
    Quantity: "176",
    "Purchase Price": "56.50",
    "Selling Price": "59",
    Profit: "=E7-D7",
    "Last Updated": "2/2/20",
    Rating: "4.5",
  },
  {
    "Item Code": "BD121M",
    "Item Name": "Table Lamp",
    Quantity: "0",
    "Purchase Price": "22.50",
    "Selling Price": "25",
    Profit: "=E8-D8",
    "Last Updated": "11/11/19",
    Rating: "5.0",
  },
  {
    "Item Code": "AT992X",
    "Item Name": "Document Scanner",
    Quantity: "116",
    "Purchase Price": "175",
    "Selling Price": "177",
    Profit: "=E9-D9",
    "Last Updated": "4/13/19",
    Rating: "4.75",
  },
  {
    "Item Code": "AP992Z",
    "Item Name": "Gaming Headset",
    Quantity: "58",
    "Purchase Price": "32",
    "Selling Price": "35",
    Profit: "=E10-D10",
    "Last Updated": "2/14/20",
    Rating: "4.4",
  },
  {
    "Item Code": "AW920X",
    "Item Name": "Laptop Bag",
    Quantity: "232",
    "Purchase Price": "18.90",
    "Selling Price": "19",
    Profit: "=E11-D11",
    "Last Updated": "6/10/19",
    Rating: "3.9",
  },
  {
    "Item Code": "AQ920Z",
    "Item Name": "Table Fan",
    Quantity: "405",
    "Purchase Price": "33.90",
    "Selling Price": "35",
    Profit: "=E12-D12",
    "Last Updated": "5/28/19",
    Rating: "3.75",
  },
  {
    "Item Code": "AE940X",
    "Item Name": "Electric Mop",
    Quantity: "47",
    "Purchase Price": "153.50",
    "Selling Price": "155",
    Profit: "=E13-D13",
    "Last Updated": "12/18/19",
    Rating: "3.9",
  },
  {
    "Item Code": "UI152C",
    "Item Name": "Smart LED TV",
    Quantity: "232",
    "Purchase Price": "201.25",
    "Selling Price": "204",
    Profit: "=E14-D14",
    "Last Updated": "3/13/20",
    Rating: "4.35",
  },
  {
    "Item Code": "UD152V",
    "Item Name": "Robotic Vacuum Cleaner",
    Quantity: "210",
    "Purchase Price": "182.25",
    "Selling Price": "185",
    Profit: "=E15-D15",
    "Last Updated": "8/26/19",
    Rating: "4.0",
  },
  {
    "Item Code": "BK120L",
    "Item Name": "Gaming Mouse",
    Quantity: "225",
    "Purchase Price": "34.80",
    "Selling Price": "38",
    Profit: "=E16-D16",
    "Last Updated": "1/12/20",
    Rating: "4.2",
  },
  {
    "Item Code": "UF162V",
    "Item Name": "Chair",
    Quantity: "373",
    "Purchase Price": "104.800",
    "Selling Price": "108",
    Profit: "=E17-D17",
    "Last Updated": "4/12/19",
    Rating: "3.25",
  },
  {
    "Item Code": "UR162C",
    "Item Name": "Welding Gloves",
    Quantity: "216",
    "Purchase Price": "19",
    "Selling Price": "21",
    Profit: "=E18-D18",
    "Last Updated": "11/22/19",
    Rating: "3.85",
  },
];

export const GDPData = [
  {
    Country: "USA",
    "Year 2017": "18.00",
    "Year 2018": "20.40",
    "Year 2019": "21.42",
    "Year 2020": "19.48",
  },
  {
    Country: "China",
    "Year 2017": "11.00",
    "Year 2018": "14.00",
    "Year 2019": "14.32",
    "Year 2020": "12.23",
  },
  {
    Country: "Japan",
    "Year 2017": "4.4",
    "Year 2018": "5.10",
    "Year 2019": "5.08",
    "Year 2020": "4.87",
  },
  {
    Country: "Germany",
    "Year 2017": "3.3",
    "Year 2018": "4.20",
    "Year 2019": "3.84",
    "Year 2020": "3.69",
  },
  {
    Country: "India",
    "Year 2017": "2.00",
    "Year 2018": "2.85",
    "Year 2019": "2.87",
    "Year 2020": "2.65",
  },
  {
    Country: "UK",
    "Year 2017": "2.90",
    "Year 2018": "2.94",
    "Year 2019": "2.82",
    "Year 2020": "2.63",
  },
  {
    Country: "France",
    "Year 2017": "2.40",
    "Year 2018": "2.93",
    "Year 2019": "2.71",
    "Year 2020": "2.58",
  },
];
